name: Repo dispatch
on:
  push:
    branches:
      - main
jobs:
  dispatch:
    runs-on: ubuntu-latest
    name: Repository Dispatch Event
    steps:
      - name: Getting hash
        id: hash
        run: |
          echo "::set-output name=sha::$(echo ${{github.sha}} | cut -c1-8)"
          echo "Short hash is $(echo ${{github.sha}} | cut -c1-8)"

      - name: Dispatching hash to parentrepo
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{ secrets.PAT }}" \
          -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" \
          https://api.github.com/repos/Wesleyzxc/parentrepo/dispatches --data '{"event_type": "repository_dispatch", "client_payload": {"hash": "${{ steps.hash.outputs.sha }}"}}'
